slice_name: Global Avg Max Temp (°C)
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 3__table
  viz_type: big_number_total
  metric:
    aggregate: AVG
    column:
      column_name: avg_tmax_celsius
      type: column
      type_generic: null
      filterable: true
      groupby: true
      is_dttm: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: AVG(avg_tmax_celsius)
    optionName: metric_avg_tmax
    sqlExpression: null
  adhoc_filters: []
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: '.1f'
  time_format: smart_date
  extra_form_data: {}
  dashboards: []
query_context: null
cache_timeout: null
uuid: 9e8c7c5a-d8db-4df6-899d-e605879c8cff
version: 1.0.0
dataset_uuid: 21079bb5-a678-487b-b94c-5571fed99b50
