slice_name: Snowiest Countries
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 4__table
  viz_type: echarts_timeseries_bar
  x_axis: country_name
  x_axis_sort: Avg Yearly Snowfall (mm)
  x_axis_sort_asc: false
  x_axis_sort_series: value
  x_axis_sort_series_ascending: false
  metrics:
  - aggregate: AVG
    column:
      column_name: avg_yearly_snowfall_mm
      type: column
      filterable: true
      groupby: true
      is_dttm: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Avg Yearly Snowfall (mm)
    optionName: metric_snow
    sqlExpression: null
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 1000
  truncate_metric: true
  y_axis_format: SMART_NUMBER
  show_legend: false
  legendType: scroll
  legendOrientation: top
  extra_form_data: {}
  dashboards: []
query_context: null
cache_timeout: null
uuid: 6ba4bc40-b516-4144-8334-1299a1ab82d6
version: 1.0.0
dataset_uuid: 4753bf7c-a7be-4d79-8c36-f40d35588518
