slice_name: Total Observations
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 3__table
  viz_type: big_number_total
  metric:
    aggregate: SUM
    column:
      column_name: observation_count
      type: column
      type_generic: null
      filterable: true
      groupby: true
      is_dttm: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(observation_count)
    optionName: metric_total_obs
    sqlExpression: null
  adhoc_filters: []
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards: []
query_context: null
cache_timeout: null
uuid: 35c6988f-a78f-4ebf-bb6d-dac1a2de6e13
version: 1.0.0
dataset_uuid: 21079bb5-a678-487b-b94c-5571fed99b50
