#!/usr/bin/env bash
# Pack reporting/assets/** into a Helm values file (helm/reporting/values-assets.yaml)
# as chart-managed `extraConfigs`. ConfigMap keys can't contain "/", so the asset
# tree path is flattened with "__" and prefixed "asset__"; the bootstrapScript
# rebuilds the directory tree at pod startup before `superset import-directory`.
#
#   reporting/assets/databases/Warehouse.yaml
#     -> extraConfigs["asset__databases__Warehouse.yaml"]
#
# Usage:
#   reporting/scripts/build-values-assets.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ASSETS_DIR="${REPO_ROOT}/reporting/assets"
OUT="${REPO_ROOT}/helm/reporting/values-assets.yaml"

[ -d "$ASSETS_DIR" ] || { echo "ERROR: missing $ASSETS_DIR" >&2; exit 1; }

ASSETS_DIR="$ASSETS_DIR" OUT="$OUT" python3 - <<'PY'
import os, pathlib

assets = pathlib.Path(os.environ["ASSETS_DIR"])
out = pathlib.Path(os.environ["OUT"])

files = sorted(p for p in assets.rglob("*.yaml") if p.is_file())
if not files:
    raise SystemExit(f"ERROR: no yaml under {assets}")

lines = [
    "# GENERATED by reporting/scripts/build-values-assets.sh - do not edit by hand.",
    "# Superset assets (databases/datasets/charts/dashboards) mounted as a ConfigMap",
    "# and imported at pod startup via bootstrapScript (see values.yaml).",
    "extraConfigs:",
]
for f in files:
    rel = f.relative_to(assets).as_posix()          # e.g. databases/Warehouse.yaml
    key = "asset__" + rel.replace("/", "__")
    lines.append(f'  {key}: |')
    for line in f.read_text().splitlines():
        lines.append(f'    {line}' if line else "")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(files)} files)")
PY

echo "Next: helm upgrade reporting superset/superset -n os-data-platform \\"
echo "        -f helm/reporting/values.yaml -f helm/reporting/values-assets.yaml"