s3:
  secretName: storage-seaweedfs-secret
  host: storage-seaweedfs-s3
  port: 8333
  bucket: lakehouse-raw

keeper:
  replicas: 1

clickhouse:
  replicas: 1
  shards: 1
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "4"
      memory: 8Gi
  initSQL: |
    CREATE DATABASE IF NOT EXISTS temp;
    CREATE DATABASE IF NOT EXISTS raw;
    CREATE DATABASE IF NOT EXISTS cleansed;
    CREATE DATABASE IF NOT EXISTS curated;
    CREATE DATABASE IF NOT EXISTS reporting;
