apiVersion: batch/v1
kind: Job
metadata:
  name: storage-rustfs-bucket-init
  namespace: os-data-platform
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          command:
            - sh
            - -c
            - |
              mc alias set rustfs ${ENDPOINT} ${RUSTFS_ROOT_USER} ${RUSTFS_ROOT_PASSWORD}
              for bucket in ${BUCKETS}; do
                mc mb --ignore-existing rustfs/${bucket}
                echo "bucket ${bucket} ready"
              done
          env:
            - name: ENDPOINT
              value: "http://storage-rustfs-svc.os-data-platform.svc.cluster.local:9000"
            - name: BUCKETS
              value: "os-data-platform-ingestor"
            - name: RUSTFS_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: storage-rustfs-secret
                  key: RUSTFS_ROOT_USER
            - name: RUSTFS_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storage-rustfs-secret
                  key: RUSTFS_ROOT_PASSWORD
