apiVersion: v2
name: storage
description: SeaweedFS object storage with bucket initialization
type: application
version: 0.1.0
dependencies:
  - name: seaweedfs
    version: "4.35.0"
    repository: "https://seaweedfs.github.io/seaweedfs/helm"