seaweedfs:
  master:
    enabled: true
    replicas: 1
    extraArgs:
      - -volumePreallocate=false
      - -defaultReplication=000

  volume:
    enabled: true
    replicas: 1
    extraArgs:
      - -max=20
      - -preStopSeconds=0

  filer:
    enabled: true
    replicas: 1

  s3:
    enabled: true
    replicas: 1
    port: 8333
    enableAuth: true
    existingConfigSecret: storage-seaweedfs-secret
    createBuckets:
      - name: lakehouse-raw
        anonymousRead: false
