# Bucket init job config
buckets:
  - name: os-data-platform-ingestor

# RustFS subchart values
rustfs:
  mode:
    standalone:
      enabled: true
    distributed:
      enabled: false
  secret:
    existingSecret: "storage-rustfs-secret"
  storageclass:
    name: "standard"
    dataStorageSize: 20Gi
    logStorageSize: 1Gi
  ingress:
    enabled: false
  consoleIngress:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
