global:
  postgresqlSecretName: metadata-db-postgresql-secret
  postgresql:
    postgresqlHost: "metadata-postgresql"
    postgresqlPort: 5432
    postgresqlDatabase: "dagster"
    postgresqlUsername: "platform"

postgresql:
  enabled: false

ingress:
  enabled: false

dagster-user-deployments:
  enabled: true
  enableSubchart: true
  deployments:
    - name: dags
      image:
        repository: dadutra2/os-data-platform-orchestrator
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "src/definitions.py"
      port: 3030
      envSecrets:
        - name: metadata-db-postgresql-secret

dagsterWebserver:
  replicaCount: 1

dagsterDaemon:
  enabled: true

dagsterHome: |
  telemetry:
    enabled: false
