global:
  postgresqlSecretName: orchestrator-postgresql-secret

postgresql:
  enabled: false
  postgresqlHost: "metadata-postgresql"
  postgresqlUsername: "platform"
  postgresqlDatabase: "dagster"

ingress:
  enabled: false

dagster-user-deployments:
  enabled: true
  enableSubchart: true
  deployments:
    - name: dags
      image:
        repository: dadutra2/os-data-platform-orchestrator
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "src/definitions.py"
      port: 3030
      env:
        - name: SEAWEEDFS_ENDPOINT_URL
          value: "http://storage-seaweedfs-s3.os-data-platform.svc.cluster.local:8333"
      envSecrets:
        - name: metadata-db-postgresql-secret
        - name: storage-seaweedfs-secret

dagsterWebserver:
  replicaCount: 1

dagsterDaemon:
  enabled: true

dagsterHome: |
  telemetry:
    enabled: false
