# --- Gateway Connection ---
gateways:
  clickhouse:
    state_connection:
      type: postgres
      host: {{ env_var('SQLMESH_POSTGRES_HOST', 'localhost') }}
      port: 5432
      database: sqlmesh
      user: platform
      password: {{ env_var('OS_DATA_PLATFORM_METADATA_DB_PLATFORM_PASSWORD') }}

    connection:
      type: clickhouse
      host: {{ env_var('SQLMESH_CLICKHOUSE_HOST', 'localhost') }}
      port: 8123
      pretty_sql: True
      username: ""
      # concurrent_tasks: 1
      # register_comments: True
      # pre_ping: False
      # schema_differ_overrides: 
      # catalog_type_overrides: 
      # password:
      # cluster: 
      # connect_timeout: 10
      # send_receive_timeout: 300
      # query_limit: 0
      # use_compression: True
      # compression_method: 
      # connection_settings: 
      # http_proxy: 
      # verify: True
      # ca_cert: 
      # client_cert: 
      # client_cert_key: 
      # https_proxy: 
      # server_host_name: 
      # tls_mode: 
      # secure: False
      # connection_pool_options: 

default_gateway: clickhouse

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: clickhouse
  start: 2026-06-28 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
