global:
  edition: community
  auth:
    instanceAdmin:
      email: "admin@airbyte.io"
      password: "admin"
  image:
    tag: "2.0.0"
  database:
    host: "metadata-postgresql"
    port: "5432"
    name: "airbyte"
    secretName: "ingestor-postgresql-secret"
  storage:
    type: minio
    secretName: storage-rustfs-secret
    bucket:
      log: os-data-platform-ingestor
      state: os-data-platform-ingestor
      workloadOutput: os-data-platform-ingestor
    minio:
      endpoint: "http://storage-rustfs-svc.os-data-platform.svc.cluster.local:9000"
      accessKeyIdSecretKey: "RUSTFS_ROOT_USER"
      secretAccessKeySecretKey: "RUSTFS_ROOT_PASSWORD"

postgresql:
  enabled: false

minio:
  enabled: false

connector-builder-server:
  enabled: false

cron:
  enabled: false

server:
  replicaCount: 1

worker:
  replicaCount: 1
