name: validate config

on:
  push:
    paths:
      - "configuration/**"
      - "libs/**"
  pull_request:
    paths:
      - "configuration/**"
      - "libs/**"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v5

      - name: Install common library
        run: uv pip install --system ./libs

      - name: Validate configs
        run: python .github/scripts/validate_config.py configuration
